# -*- coding: utf-8 -*-
"""Untitled2.ipynb의 사본

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19YvQsVzN1o6rEqlDIRmLLJn_hNeEv2eH
"""

#1000
a,b = input().split()
a= int(a)
b=int(b)
print(a+b)

#2557
print("Hello World!")

#10171
print("\\    /\\")
print(" )  ( \')")
print("(  /  )")
print(" \\(__)|")

#10171
a, b = map(int, input().split())
print(a+b)
print(a-b)
print(a*b)
print(a//b)
print(a%b)
print(*divmod(a,b))

#9498
score = int(input())
if 90 <= score <= 100:
  print('A')
elif 80 <= score < 90:
  print('B')
elif 70 <= score < 80:
  print('C')
elif 60 <= score < 70:
  print('D')
else:
  print('F')

#2752
num = list(map(int, input().split()))
num.sort()
for i in num:
  print(i, end=' ')

print(' '.join(map(str, sorted(list(map(int, input().split()))))))

#2753
year = int(input())
if year%4==0 and year%100 !=0 :
  print(1)
elif year%400==0:
  print('1')
else:
  print('0')

year = int(input())
if (year%4==0 and year%100 !=0) or year%400==0:
  print(1)
else:
  print('0')

#2490
for _ in range(3):
  s=  list(map(int,input().split()))
  if s.count(1) == 0:
    print('D')
  elif s.count(1) == 1:
    print('C')
  elif s.count(1) == 2:
    print('B')
  elif s.count(1) == 3:
    print('A')
  elif s.count(1) == 4:
    print('E')

#2562
num = []
for i in range(9):
    num.append(int(input()))
print (max(num))
print (num.index(max(num))+1)

#2576

#2587
import statistics
num=[]
for _ in range(5):
  num.append(int(input()))
print(statistics.mean(num))
print(statistics.median(num))

#2309

#10093

#2577
n=str(int(input())*int(input())*int(input()))
for i in range(10):
  print(n.count(str(i)))

#1267
n=int(input())
time =[]
time.extend(map(int, input().split(" ")));
Y=0
M=0
for i in time:
  Y +=int((i/30)+1)*10
  M +=int((i/60)+1)*15
  
if Y>M:
   print("M %d" %(M))
elif M>Y:
   print("Y %d" %(Y))
else:
   print ("Y M %d" %(M))

#10804
numbers = list(range(1,21))
for i in range(10):
    a,b = map(int,input().split())
    numbers = numbers[:a-1] + list(reversed(numbers[a-1:b])) + numbers[b:]
print(' '.join(list(map(str,numbers))))

a,b,c = map(int,input().split())
if a==b==c:
  print(10000+a*1000)
elif a!=b!=c:
  print(max(a,b,c)*100)
else:
  if a==b or a==c:
    print(1000+a*100)
  elif b==c:
    print(1000+b*100)

a,b,c = map(int, input().split())
if a == b and a == c:
    print ((a * 1000) + 10000)
elif a != b and a != c and b != c:
    print (max(a, b, c) * 100)
else:
    if a == b:
        print (a * 100 + 1000)
    elif a == c:
        print (c * 100 + 1000)
    elif b == c:
        print (b * 100 + 1000)

for _ in range(3):
  s=  list(map(int,input().split()))
  if s.count(1) == 0:
    print('D')
  elif s.count(1) == 1:
    print('C')
  elif s.count(1) == 2:
    print('B')
  elif s.count(1) == 3:
    print('A')
  elif s.count(1) == 4:
    print('E')

exec("print('EABCD'[input().count('0')]);" * 3)

num = list(map(int, input().split("\n")))
print(max(num))
print(num.index(max(num))+1)

l=[0]
exec("l.append(int(input()));"*9)
print(l)

num = []
for i in range(7):
  num.append(int(input())) 
n=list(filter(lambda x: x % 2, num))
s=sum(n)
if s > 0:
  print(s)
else:
  print(-1)
print(min(n))

import statistics
num=[]
for _ in range(5):
  num.append(int(input()))
print(statistics.mean(num))
print(statistics.median(num))

import sys

n=[int(input(sys.stdin.readline())) for i in range(7)]
s=sum(list(filter(lambda x: x % 2, n)))
if s > 0:
  print(s)
else:
  print(-1)
print(min(n))

import sys
height = [int(input(sys.stdin.readline())) for i in range(9)]

height.sort()
total=sum(height)

for i in range(len(height)):
  for j in range(i+1,len(height)):
    if total-height[i]-height[j]==100:
       for k in range(9):
          if i == k or j == k:
            continue
          print(height[k])

height=[]
for i in range(9):
  height.append(int(input()))

height.sort()
total=sum(height)

for i in range(len(height)):
  for j in range(i+1,len(height)):
    if total-height[i]-height[j]==100:
       for k in range(9):
          if i == k or j == k:
            continue
          print(height[k])

a,b = map(int,input().split())
if a< b:
  print(b-a-1)
elif a>b:
  print(a-b-1)
else:
  print(0)
for i in range(a+1,b):
  print(i, end='')

for i in range(9,14):
  print(i)

a=int(input())
b=int(input())
c=int(input())

n=str(int(input())*int(input())*int(input()))
for i in range(10):
  print(n.count(str(i)))

#1267 핸드폰 요금
 
n = int(input());
time = []
time.extend(map(int, input().split(" ")));
YeongSik = 0;
MinSik = 0;
 
for t in time:
    YeongSik += int((t/30)+1)*10;
    MinSik += int((t/60)+1)*15;
 
if YeongSik > MinSik:
    print ("M %d" );
elif YeongSik < MinSik:
    print ("Y %d" );
else: print ("Y M %d" );

n=int(input())
time =[]
time.extend(map(int, input().split(" ")));
Y=0
M=0
for i in time:
  Y +=int((i/30)+1)*10
  M +=int((i/60)+1)*15
  
if Y>M:
   print("M %d" %(M))
elif M>Y:
   print("Y %d" %(Y))
else:
   print ("Y M %d" %(M))

l,=range(21);exec('a,b=map(int,input().split());l[a:b+1]=l[b:a-1:-1];'*10);print(*l[1:])

cards = range(1,21)
for i in range(10):
    a,b = map(int,input().split())
    cards = cards[:a-1]+list(reversed(cards[a-1:b]))+cards[b:]
print ' '.join([str(x) for x in cards])

numbers = list(range(1,21))
for i in range(10):
    a,b = map(int,input().split())
    numbers = numbers[:a-1] + list(reversed(numbers[a-1:b])) + numbers[b:]
print(' '.join(list(map(str,numbers))))

numbers = [x for x in range(1,21)]
for i in range(10):
    start,stop = map(int,input().split())
    start -= 1
    numbers = numbers[:start] + numbers[start:stop][::-1] + numbers[stop:]
print(' '.join(list(map(str,numbers))))

a=int(input())
for i in range(1,a+1):
    print("*"*i)

a=int(input())
for i in range(1,a+1):
    print("*"*(a-i+1))

a=int(input())
for i in range(1,a+1):
    print(" "*(a-i) + "*"*i)

a=int(input())
for i in range(1,a+1):
    print(" "*(i-1) + "*"*(a-i+1))

a=int(input())
for i in range(1,a+1):
  print(' '*(a-i)+'*'*(2*i-1))

a=int(input())
for i in range(1,a+1):
  print(' '*(i-1)+'*'*(2*(a-i)+1))

a=int(input())
for i in range(1,a+1):
  print(' '*(a-i)+'*'*(2*i-1))
for i in range(1,a):
  print(' '*(i)+'*'*(2*(a-i-1)+1))

a=int(input())
for i in range(1,a+1):
  print('*'*i+' '*(2*(a-i))+'*'*i)
for i in range(1,a):
  print('*'*(a-i)+' '*(2*i)+'*'*(a-i))

a=int(input())
for i in range(1,a+1):
  print(' '*(i-1)+'*'*(2*(a-i)+1))
for i in range(1,a):
  print(' '*(a-i-1)+'*'*(2*i+1))

n=input()
for i in ['a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z']
  print(n.count(i))

import string
n=input()

for i in [c for c in string.ascii_lowercase]:
  print(n.count(i), end=' ')



