# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1k3ZfH0gHUPa9IdKiVZPXm0VtdTIH4px5
"""

import heapq
import sys;
heap=[]
for i in range(int(sys.stdin.readline())):
    element=int(sys.stdin.readline())
    if element==0:
        print(heapq.heappop(heap)[0]if lis else 0)
    else:
        heapq.heappush(heap,(abs(element),element))